## GET  /products
GET http://{{server}}:{{port}}/api/users


### POST /users
POST http://{{server}}:{{port}}/api/users/register
Content-Type: application/json

{
  "email": "adsa@dsa.ua",
  "password": "SdcaASD123SD_dsadas"
}


